### ISSUE TITLE
月間レポートの作成

### ISSUE THREAD

**Issue by BlueKanbu** [Odacchi/fcoin-user-manual#20]
協力して、完成しましょう。

**Comment by YOUFCoin** [comment]
おおまかな構成はこんな感じで。

📌挨拶とまえがき
📌チームのミッション
📌やったことの概要
    ・チームビルディング
    ・チーム開発のためにGitHubでの開発運用
    ・全部中国語化
    ・そのほかアップデート
📌PR結果

📌やったことの詳細や補足
📌FCoinトリセツについて

**Comment by YOUFCoin** [comment]
前回の
https://ft.fan/forum.php?mod=viewthread&tid=2757&page=1&extra=#pid17927
2回目の
https://ft.fan/forum.php?mod=viewthread&tid=2610&page=1&extra=#pid16906

**Comment by KouBT** [comment]
📌挨拶とまえがき
こんにちは、コミュニティのみなさん。私たちは PRノード (PR Node ) です。今回で、4回目の投稿となります。
今回も、FCoinトリセツの開発状況の報告と、集客状況、また、TwitterでのPR結果を報告します。
今回から、PRマイニング形式の変更により、FCoinトリセツは月間レポートになります。

📌チームのミッション
📌やったことの概要
・チームビルディング
・チーム開発のためにGitHubでの開発運用
・全部中国語化
・そのほかアップデート
📌PR結果

📌やったことの詳細や補足
📌FCoinトリセツについて

**Comment by BlueKanbu** [comment]
鬼すぎんさんの訂正により：


ミッション：
FCoinに関する情報等をまとめて日本語・中国語・英語で発信していきます。誰もがFCoinについて簡単に理解できFCoinを利用する際のトラブル・不明な点をトリセツで解決できるように。またFCoinの顧客満足度を高めることで、FCoinコミュニティおよびFCoin日本コミュニティの発展に貢献する。今後は仮想通貨の用語集・トリセツ辞典も開発致します。

**Comment by BlueKanbu** [comment]
📌挨拶とまえがき

こんにちは、コミュニティのみなさん。私たちは FCoin Manual Lab ノード です（色々な原因で、PR node の名を借りて参加しました）。4回目の投稿となります。
今回も、FCoinトリセツの開発状況の報告と、集客状況、また、TwitterでのPR結果を報告します。
今回から、PRマイニング形式の変更により、FCoinトリセツは月間レポートになってきました。

📌チームのミッション

ミッション：
FCoinに関する情報等をまとめて日本語・中国語・英語で発信していく。誰もがFCoinについて簡単に理解できFCoinを利用する際のトラブル・不明な点をトリセツで解決できるように。またFCoinの顧客満足度を高めることで、FCoinコミュニティおよびFCoin日本コミュニティの発展に貢献する。今後は仮想通貨の用語集・トリセツ辞典も開発する。

📌やったことの概要
・チームビルディング
まずは、新しいPRマイニングの形と合わせるために、PRチームを立ち上げた。PRチームには、ウェブ開発のエンジニア、中国語と日本語を身につける訳者、FCoinのことをよく理解する有志者、またはコミュニティで人気のある方、ツィターでのプロモーションに集中する方が揃った。

・チーム開発のためにGitHubでの開発運用
チームワークを効率的になるため、Githubでissueなどの機能を利用し、協力作業していた。

・全部中国語化
今月では、「マイニング詳細」、「よくある質問」、「リンク集」3つのページの内容を中国語に翻訳した。これで、前回中国語化された「トップページ」、「3分でFCoinのサービスを理解するページ」を含めて、FCoinトリセツの中国語化作業が一時的に完成した。

・そのほかアップデート
📌PR結果

📌やったことの詳細や補足
📌FCoinトリセツについて

**Comment by YOUFCoin** [comment]
📌问候和介绍
社区的各位，你们好。 我们是FCoin Manual Lab 推广节点（由于一些原因变成了PR node的名称）。 这是我们投稿的第4个帖子（结合规则改变之前的投稿）。
这一次，我们还将报告【FCoin 说明书】的发展状况，包括吸引了多少浏览量，以及其他在推特上推广的结果。
从那时起，由于推广挖矿形式的变化，【FCoin 说明书】的成果汇报也变成月度报告。还请各位悉知。
📌团队使命
我们的使命：
将有关FCoin的信息以日语，中文和英语三国语言的形式，进行汇总和传播。我们的目的是，当你在使用【FCoin 说明书】时，能够帮助你迅速找到想要的信息，并且以通俗易懂的解说让你领会，从而解决你的问题。我们期望能够通过我们还将通过【FCoin 说明书】提高用户对FCoin的满意度，为FCoin社区和FCoin日本社区的发展做出贡献。 在未来，我们也有可能开发虚拟货币词典和【FCoin 说明书】词典（当然如果能得到大家的支持，我相信实现会更快）。
📌所做之事的总结
・组建团队
我们建立了一个推广团队，以匹配新的推广挖矿规则。团队包括网络开发工程师，文稿编辑，多语言翻译等角色。每个人都是陪伴FCoin成长的老用户，或是在社区中受欢迎的用户，或是擅长在推特等自媒体平台上宣传的人员。
・使用GitHub进行团队工作的开发和操作
为了提高团队工作效率，使用了Github中诸如issue之类的协作功能。
・全部中文化
在这个月，我们将“挖掘细节”，“常见问题”和“常见链接”这三个页面的内容翻译成了中文。 现在，包括“中文首页”和“3分钟了解FCoin页面”，【FCoin 说明书】的中文版已经完成（当然会随着今后内容的补充不断更新）
・其他补充
📌推广成果
📌所做之事的具体内容
根据完成的issue，所做的事情如下：
【TRX杠杆理财介绍页面的追加】
将TRX追加到理财账户和杠杆交易支持的货币列表中。
【3分钟了解FCoin页面中添加内容的中文翻译】

翻译了邀请挖矿的介绍部分
【说明书中的错别字修改，规则更新】
发现并纠正了已经说明书中的错别字。
【常见问题的翻译】
所有内容都翻译成中文，内容随着规则的变化而得到纠正。
【更新在首页的“关于FT”】。
随着Fractal公链的发布，FT已经从平台币升级为公链币，因此我们针对此更新了FT的定义描述。
【应对分红锁仓的升级】
注明了分红锁仓不再参与锁仓挖矿的信息。
【追加邀请挖矿说明页面 】
追加邀请挖矿说明图解，说明文字。
【完成挖矿详解页面的中文翻译】
完成挖矿详解页面的中文翻译，并将其中的一些链接也换成对应的中文链接。
📌关于【FCoin 说明书】
与FCoin强调“公开透明”和“社区化”的理念一致，基于GitHub上的开源开发，并使用一种名为GitHub Pages的机制。
但是不足的是，由于没有宣传经费，目前还没有发布广告进行宣传（GitHub上面可以自己出钱买广告位，用于大范围的推广）。当然，我也不会考虑利用【FCoin 说明书】进行盈利活动，一切只是忠于我为FCoin社区服务的公心。
另外，因为它是开源的，所以也可以与其他人共同开发。
但是，我们花了很多精力和时间在【FCoin 说明书】上，如果大家认可我们的工作，支持我们获得推广挖矿奖励的话，我们才有更多的可能性去完善好【FCoin 说明书】。
与博客，公众号这些不同，【FCoin 说明书】只白描事实，而不发表私人的预测或意见。
因此，【FCoin 说明书】的作用不仅仅是在新用户涌入FCoin方面做出贡献，也在提高用户的满意度减少取关率方面贡献自己的力量。我们希望通过自己的努力推动FCoin社区的发展。
通过【FCoin 说明书】，我们希望能增加深度了解FCoin的FTer，从而加强FCoin社区建设，并从长远增加FTer的整体利益。
【FCoin 说明书】首页：
 https://www.fcoin-manual.com
GitHub的开发页面：
 https://github.com/Odacchi/fcoin-user-manual
【FCoin 说明书】的未来：
我们将增加如何使用和查看FCoin的每个页面的引导内容。
我们将补充“常见问题”页面，并将其内容提供给电报中有疑问的用户。
我们将不断扩大和整理内容。
我们将改进用户界面和用户体验。

**Comment by GSHT007** [comment]
📌Greetings 

 Hello, everyone.  We are FCoin Manual Lab node (we joined as the name of PR node for some reasons).  This time is the 4th post our report.
 This time, also we will report the development status of FCoin Torisetsu (=manual in Japanese), the customer attendance status, and the results of PR on Twitter.
 From this time, due to the change in the way for PR mining, FCoin Torisets has become a monthly report.

**Comment by GSHT007** [comment]
時間見つけて英訳していきますね！

**Comment by YOUFCoin** [comment]
Hello everyone. We are the FCoin Manual Lab promotion node (somehow we got the  name of the PR node).
This time, we will also report on the development of the [FCoin Manual], including how many viewswu got, and other achievements.
By the way, the results report of the [FCoin Manual] has also become a monthly report due to changes of the promotion mining forms.

Team mission
Our mission:
Summary and disseminate  information about FCoin in the form of Japanese, Chinese and English. Our goal is to help user quickly find the information what he or she wants  using the [FCoin Manual], and let t he or she understand it with easy-to-understand explanations. We hope that we will also contribute to the development of the FCoin community and the FCoin Japanese community through our [FCoin Manual] which can increase user satisfaction with FCoin. In the future, we may also develop a virtual currency dictionary and  [FCoin manual] dictionary  (of course, if we can get the awards of promotion,we can do better ).

About [FCoin Manual]
Consistent with FCoin's principle of “open and transparency” and “community-based”, furthermore based on open source development on GitHub(it can also be developed with others), and working by using a managing implement called GitHub Pages.
However, the shortcoming is that there is currently no advertisement for further promotion. Of course, I will not consider using  [FCoin manual] for profitable activities. But we spent a lot of energy and time on the [FCoin manual] and we need financial support to perfect  [FCoin manual].
If you recognize our work and be willing to support us,please vote for [FCoin manual].
Unlike blogs and other public selfmedias, [FCoin manual] only describes facts and does not publish private forecasts or opinions.
Therefore, the role of the [FCoin Manual] is not only to contribute to the influx of new users into FCoin, but also to contribute to improving user satisfaction. We hope to promote the development of the FCoin community through our own efforts.
Through the [FCoin M anual], we hope to increase the number of FCoin's FTer who know FCoin well , thereby strengthening the FCoin community and increasing the overall benefits of FTer in the long term.
Here are some links:
[FCoin Manual] home page:
https://www.fcoin-manual.com
GitHub development page:
https://github.com/Odacchi/fcoin-user-manual

**Comment by Odacchi** [comment]
完了済みのためクローズ

19位お疲れ様でした。
